@host=localhost:4000
@jwt=eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6WyJ1c2VyOmNhbnVwbG9hZDphZGhvY21lc3NhZ2UiLCJ1c2VyOmNhbm1hbmFnZTp1c2VycyIsInVzZXI6Y2FuZG93bmxvYWQ6ZmlsZXMiLCJ1c2VyOmNhbmFsdGVyX2JhY2t1cF9wb2xpY3kiLCJ1c2VyOmNhbmFsdGVyOm1lc3NhZ2UiLCJST0xFX0FETUlOIiwidXNlcjpjYW5kaXNhYmxlOnB1Ymxpc2hpbmciXSwiZXhwIjoxNzAwMDY1MzYwLCJpYXQiOjE3MDAwMjkzNjAsInVzZXJuYW1lIjoiYWRtaW4ifQ.mCUhR5elxU6ATli04uGidQ1pkxiG3RVnkVS9ITkKpRs

### Get AAA Outages + Remedy First Query
POST http://{{host}}/api/charts/aaa_outages_plus_remedy_query1
Content-Type: application/json
Authorization: {{jwt}}

    {"dateRange":
        {
        "startDate": "2023-10-01T00:00:00.000+02:00",
        "endDate": "2023-10-05T00:00:00.000+02:00"
        }
    }

###
### Get AAA Outages + Remedy Second Query
POST http://{{host}}/api/charts/aaa_outages_plus_remedy_query2
Content-Type: application/json
Authorization: {{jwt}}

{ 
    "dateRange":
        {
             "startDate":"2023-10-01T00:00:00.000+02:00",
             "endDate":"2023-10-19T00:00:00.000+02:00"
        }
}

###
POST http://{{host}}/api/charts/num_of_requests_per_method
Content-Type: application/json
Authorization: {{jwt}}

{
    "dateRange":
        {
             "startDate":"2023-10-01T00:00:00.000+02:00",
             "endDate":"2023-10-19T00:00:00.000+02:00"
        }
}

###
POST http://{{host}}/api/charts/aaa_outages_top_affected_areas
Content-Type: application/json
Authorization: {{jwt}}

{
    "dateRange": {
    "startDate": "2023-11-01T22:00:00.000+02:00",
    "endDate": "2023-11-01T22:00:00.000+02:00"
    }
}


###
POST http://{{host}}/api/charts/aaa_avg_outages_perday_uniq_dslam_sess_affacted
Content-Type: application/json
Authorization: {{jwt}}

{
    "dateRange": {
    "startDate": "2023-11-01T00:00:00.000+02:00",
    "endDate": "2023-11-03T00:00:00.000+02:00"
    }
}

###
POST http://{{host}}/api/charts/remedy_tickets_per_resolution
Content-Type: application/json
Authorization: {{jwt}}

{
    "dateRange": {
    "startDate": "2023-11-01T00:00:00.000+02:00",
    "endDate": "2023-11-03T00:00:00.000+02:00"
    }
}

###
POST http://{{host}}/api/charts/getTopXSitesAllTechs
Content-Type: application/json
Authorization: {{jwt}}

{
    "dateRange": {
    "startDate": "2023-11-01T00:00:00.000+02:00",
    "endDate": "2023-11-03T00:00:00.000+02:00"
    }
}

# http://yourhost/proxy/dslam-outage?from=2023-11-01&to=2023-11-02
###
GET http://{{host}}/api/charts/proxy/dslam-outage?from=2023-11-01&to=2023-11-02
# Content-Type: application/json
# Authorization: {{jwt}}

###
POST http://localhost:4000/api/charts/nova_num_of_requests_per_method
Content-Type: application/json
# Authorization: {{jwt}}

{
    "dateRange": {
        "startDate": "2023-10-14T21:00:00.000Z",
        "endDate": "2023-11-14T22:00:00.000Z"
    }
}