@host=localhost:4000
@jwt=Bearer: eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6WyJ1c2VyOmNhbnVwbG9hZDphZGhvY21lc3NhZ2UiLCJ1c2VyOmNhbm1hbmFnZTp1c2VycyIsInVzZXI6Y2FuZG93bmxvYWQ6ZmlsZXMiLCJ1c2VyOmNhbmFsdGVyX2JhY2t1cF9wb2xpY3kiLCJ1c2VyOmNhbmFsdGVyOm1lc3NhZ2UiLCJST0xFX0FETUlOIiwidXNlcjpjYW5kaXNhYmxlOnB1Ymxpc2hpbmciXSwiZXhwIjoxNjk5NzEzNTQ1LCJpYXQiOjE2OTk2Nzc1NDUsInVzZXJuYW1lIjoiYWRtaW4ifQ.Qd7fTWWXHYqx7o4tXJ6oNgjkwETT2b9FVfOL6R0eVYI

### Get AAA Outages + Remedy First Query
POST http://{{host}}/api/charts/aaa_outages_plus_remedy_query1
Content-Type: application/json
Authorization: {{jwt}}

    {"dateRange":
        {
        "startDate": "2023-10-01T00:00:00.000Z",
        "endDate": "2023-10-05T23:59:59.000Z"
        }
    }

###
### Get AAA Outages + Remedy Second Query
POST http://{{host}}/api/charts/aaa_outages_plus_remedy_query2
Content-Type: application/json
Authorization: {{jwt}}

{ 
    "dateRange":
        {
             "startDate":"2023-10-01T04:45:22.373Z",
             "endDate":"2023-10-19T05:45:22.373Z"
        }
}

###
POST http://{{host}}/api/charts/num_of_requests_per_method
Content-Type: application/json
Authorization: {{jwt}}

{
    "dateRange":
        {
             "startDate":"2023-10-01T04:45:22.373Z",
             "endDate":"2023-10-19T05:45:22.373Z"
        }
}

###
POST http://{{host}}/api/charts/aaa_outages_top_affected_areas
Content-Type: application/json
Authorization: {{jwt}}

{
    "dateRange": {
    "startDate": "2023-11-01T22:00:00.000Z",
    "endDate": "2023-11-01T22:00:00.000Z"
    }
}