### Get AAA Outages + Remedy First Query
POST http://localhost:4000/api/charts/aaa_outages_plus_remedy_query1
Content-Type: application/json
Authorization: Bearer: eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6WyJ1c2VyOmNhbnVwbG9hZDphZGhvY21lc3NhZ2UiLCJ1c2VyOmNhbm1hbmFnZTp1c2VycyIsInVzZXI6Y2FuZG93bmxvYWQ6ZmlsZXMiLCJ1c2VyOmNhbmFsdGVyX2JhY2t1cF9wb2xpY3kiLCJ1c2VyOmNhbmFsdGVyOm1lc3NhZ2UiLCJST0xFX0FETUlOIiwidXNlcjpjYW5kaXNhYmxlOnB1Ymxpc2hpbmciXSwiZXhwIjoxNjk5NTY1MTYyLCJpYXQiOjE2OTk1MjkxNjIsInVzZXJuYW1lIjoiYWRtaW4ifQ.CFuTllw2hjakf6GDpk1vboTMJP1ePJwl6TxOkarkWtQ

    {"dateRange":
        {
            "startDate":"2023-10-01T04:00:00.000Z",
            "endDate":"2023-10-03T03:00:00.000Z"
        }
    }

###
### Get AAA Outages + Remedy Second Query
POST http://localhost:4000/api/charts/aaa_outages_plus_remedy_query2
Content-Type: application/json
Authorization: Bearer: eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6WyJ1c2VyOmNhbnVwbG9hZDphZGhvY21lc3NhZ2UiLCJ1c2VyOmNhbm1hbmFnZTp1c2VycyIsInVzZXI6Y2FuZG93bmxvYWQ6ZmlsZXMiLCJ1c2VyOmNhbmFsdGVyX2JhY2t1cF9wb2xpY3kiLCJ1c2VyOmNhbmFsdGVyOm1lc3NhZ2UiLCJST0xFX0FETUlOIiwidXNlcjpjYW5kaXNhYmxlOnB1Ymxpc2hpbmciXSwiZXhwIjoxNjk5NTY1MTYyLCJpYXQiOjE2OTk1MjkxNjIsInVzZXJuYW1lIjoiYWRtaW4ifQ.CFuTllw2hjakf6GDpk1vboTMJP1ePJwl6TxOkarkWtQ

{ 
    "dateRange":
        {
             "startDate":"2023-10-01T04:45:22.373Z",
             "endDate":"2023-10-19T05:45:22.373Z"
        }
}

###
POST http://localhost:4000/api/charts/num_of_requests_per_method
Content-Type: application/json
Authorization: Bearer: eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6WyJ1c2VyOmNhbnVwbG9hZDphZGhvY21lc3NhZ2UiLCJ1c2VyOmNhbm1hbmFnZTp1c2VycyIsInVzZXI6Y2FuZG93bmxvYWQ6ZmlsZXMiLCJ1c2VyOmNhbmFsdGVyX2JhY2t1cF9wb2xpY3kiLCJ1c2VyOmNhbmFsdGVyOm1lc3NhZ2UiLCJST0xFX0FETUlOIiwidXNlcjpjYW5kaXNhYmxlOnB1Ymxpc2hpbmciXSwiZXhwIjoxNjk5NTY1MTYyLCJpYXQiOjE2OTk1MjkxNjIsInVzZXJuYW1lIjoiYWRtaW4ifQ.CFuTllw2hjakf6GDpk1vboTMJP1ePJwl6TxOkarkWtQ

{
    "dateRange":
        {
             "startDate":"2023-10-01T04:45:22.373Z",
             "endDate":"2023-10-19T05:45:22.373Z"
        }
}